### ISSUE TITLE
Script get_data.sh is broken

### ISSUE THREAD

**Issue by gregorjerse** [artetxem/vecmap#24] opened 2019-04-04 17:15 UTC
It fails to download the file 

http://clic.cimec.unitn.it/~georgiana.dinu/down/resources/transmat.zip

due to server named clic.cimec.unitn.it not being resolvable.
Has it been renamed?

**Comment by loonghuey** [comment] 2019-04-13 01:51
Alternative download path:

[https://dl.fbaipublicfiles.com/arrival/dictionaries/OPUS_en_it_europarl_train_5K.txt](https://dl.fbaipublicfiles.com/arrival/dictionaries/OPUS_en_it_europarl_train_5K.txt)
[https://dl.fbaipublicfiles.com/arrival/dictionaries/OPUS_en_it_europarl_test.txt](https://dl.fbaipublicfiles.com/arrival/dictionaries/OPUS_en_it_europarl_test.txt)

**Comment by yigitsever** [comment] 2019-05-04 14:44
embeddings are gone as well

**Comment by sebpuetz** [comment] 2019-06-22 10:53
I was able to find more of the missing datasets over at https://github.com/benathi/multisense-prob-fasttext/tree/master/data/word_similarity_datasets/wordsim_foreign_clean/crosslingual

Did anyone find something on the missing word embeddings? All I could find was links to pan.baidu.com links at https://rare-technologies.com/translation-matrix-in-gensim-python/ and it seems like it requires registering.

**Comment by yigitsever** [comment] 2019-06-23 09:49
I had cloned and used the repo while the script was working and have 
de.emb.txt
en.emb.txt
es.emb.txt
fi.emb.txt
it.emb.txt
on my machine, I can upload them somewhere but can't host them reliably. If someone want to help with that please get in touch.

**Comment by sebpuetz** [comment] 2019-06-23 09:56
`en.emb.txt` and `it.emb.txt` would be awesome, that should be the last missing bits!

**Comment by yigitsever** [comment] 2019-06-23 15:37
I have uploaded two embedding files to firefox send;
https://send.firefox.com/download/783310142e588b6c/#AREl1HHgElpOMy9YeOSUxA

Expires after 7 days or 100 downloads

**Comment by sebpuetz** [comment] 2019-06-23 15:41
Awesome, thank you very much!

**Comment by sebpuetz** [comment] 2019-06-23 16:57
@yigitsever 
~~Sorry to bother you again, but it seems like firefox send has issues with actually delivering files bigger than 1GB. https://github.com/mozilla/send/issues/1351
The download cancels everytime after 50%, tested on different machines. Could you reupload the files at https://wetransfer.com/ or another hosting service?~~

Tried again, this time the download went through.

**Comment by ZYLpro** [comment] 2019-06-29 14:29
> 我已经克隆并在脚本运行时使用了repo并且 在我的机器上有
> de.emb.txt 
> en.emb.txt 
> es.emb.txt 
> fi.emb.txt 
> it.emb.txt 
> ，我可以将它们上传到某个地方但是可以不可靠地托管它们。如果有人想帮忙，请与我们联系。



> I had cloned and used the repo while the script was working and have
> de.emb.txt
> en.emb.txt
> es.emb.txt
> fi.emb.txt
> it.emb.txt
> on my machine, I can upload them somewhere but can't host them reliably. If someone want to help with that please get in touch.

hello, i cannot download en.emb.txt and it.emb.txt with the 'https://send.firefox.com/download/783310142e588b6c/#AREl1HHgElpOMy9YeOSUxA'   because of permission.  Can you share me the data with another method? thanks!!

**Comment by ZYLpro** [comment] 2019-06-29 14:30
> @yigitsever
> ~Sorry to bother you again, but it seems like firefox send has issues with actually delivering files bigger than 1GB. [mozilla/send#1351](https://github.com/mozilla/send/issues/1351) The download cancels everytime after 50%, tested on different machines. Could you reupload the files at https://wetransfer.com/ or another hosting service?~
> 
> Tried again, this time the download went through.

hello, i cannot download en.emb.txt and it.emb.txt with the 'https://send.firefox.com/download/783310142e588b6c/#AREl1HHgElpOMy9YeOSUxA'   because of permission.  Can you share me the data with another method? thanks!!

**Comment by yigitsever** [comment] 2019-06-29 15:32
https://we.tl/t-i61TFhDiTY is en.emb.txt and https://we.tl/t-Os5kszVkJ0 is it.emb.txt @ZYLpro

**Comment by ZYLpro** [comment] 2019-06-30 01:11
> https://we.tl/t-i61TFhDiTY is en.emb.txt and https://we.tl/t-Os5kszVkJ0 is it.emb.txt @ZYLpro

thanks!!

**Comment by artetxem** [comment] 2019-07-01 21:38
This should be fixed in b82246f6c249633039f67fa6156e51d852bd73a3

This was caused by the website of Dinu et al. (2015) being down, but I got the permission from the authors to redistribute their dataset.

**Closed as completed by artetxem** 2019-07-01 21:38 UTC
